# M4Utils MOTD Configuration

# MOTD Settings
motd:
  # First line of the MOTD
  line1: "&5&lPlatform Destroyer &f&l- &e&lSURVIVAL ABERTO!"

  # Second line of the MOTD
  line2: "&f✦ &fVenha se juntar à nossa comunidade! &f✦"

# Messages
messages:
  join: "&e%player% joined the game"
  quit: "&e%player% left the game"

# RTP settings
rtp:
  max-radius: 10000
  cooldown-seconds: 300

# Note: Use '&' for color codes:
# &0: Black        &1: Dark Blue    &2: Dark Green   &3: Dark Aqua
# &4: Dark Red     &5: Dark Purple  &6: Gold         &7: Gray
# &8: Dark Gray    &9: Blue         &a: Green        &b: Aqua
# &c: Red          &d: Light Purple &e: Yellow       &f: White
# &k: Magic        &l: Bold         &m: Strikethrough
# &n: Underline    &o: Italic       &r: Reset

# Configuração da Scoreboard do m4Utils
# Desenvolvido por m4nst3in

# Configurações gerais da scoreboard
scoreboard:
  # Ativar ou desativar a scoreboard
  ativada: true

  # Intervalo de atualização da scoreboard (em ticks - 20 ticks = 1 segundo)
  intervalo-atualizacao: 20

  # Título da scoreboard
  # Você pode usar múltiplos títulos que alternam no intervalo definido
  titulos:
    alternar: true
    intervalo: 40 # 2 segundos
    lista:
      - "&6&lSEU SERVIDOR"
      - "&e&lBEM-VINDO!"
      - "&6&l{player}"

# Linhas da scoreboard
# Use {player} para o nome do jogador
# Suporta PlaceholderAPI - Use % no início e fim do placeholder
linhas:
  - "&7"
  - "&fJogador: &e{player}"
  - "&fGrupo: &e%vault_group%"
  - "&fClã: &e%clans_tag%"
  - "&7"
  - "&fMoney: &e%vault_eco_balance_formatted%"
  - "&fCoins: &e%server_coins%"
  - "&7"
  - "&fKills: &a%stats_kills%"
  - "&fDeaths: &c%stats_deaths%"
  - "&7"
  - "&ewww.seuservidor.com.br"

# Configurações de visualização
visualizacao:
  # Lista de mundos onde a scoreboard será mostrada
  mundos-ativos:
    - "world"
    - "world_nether"
    - "world_the_end"

  # Lista de mundos onde a scoreboard será desativada
  mundos-desativados: []

# Permissões
permissoes:
  # Permissão para ver a scoreboard
  ver: "m4utils.scoreboard.ver"
  # Permissão para recarregar a configuração
  reload: "m4utils.scoreboard.reload"

# Mensagens do sistema
mensagens:
  reload: "&aA configuração da scoreboard foi recarregada com sucesso!"
  no-permission: "&cVocê não tem permissão para executar este comando!"
  scoreboard-toggle-on: "&aScoreboard ativada!"
  scoreboard-toggle-off: "&cScoreboard desativada!"