# M4Utils MOTD Configuration

# MOTD Settings
motd:
  # First line of the MOTD
  line1: "&5&lPlatform Destroyer &f&l- &e&lSURVIVAL ABERTO!"

  # Second line of the MOTD
  line2: "&f✦ &fVenha se juntar à nossa comunidade! &f✦"

# Messages
messages:
  join: "&e%player% joined the game"
  quit: "&e%player% left the game"

# RTP settings
rtp:
  max-radius: 10000
  cooldown-seconds: 300

# Note: Use '&' for color codes:
# &0: Black        &1: Dark Blue    &2: Dark Green   &3: Dark Aqua
# &4: Dark Red     &5: Dark Purple  &6: Gold         &7: Gray
# &8: Dark Gray    &9: Blue         &a: Green        &b: Aqua
# &c: Red          &d: Light Purple &e: Yellow       &f: White
# &k: Magic        &l: Bold         &m: Strikethrough
# &n: Underline    &o: Italic       &r: Reset