name: M4Utils
version: '1.0'
main: me.m4nst3in.m4Utils.Main
api-version: '1.21'
description: A plugin that customizes server MOTD and icon
author: M4nSt3in
depend: [LuckPerms, PlaceholderAPI]
commands:
  m4reload:
    description: Reloads the M4Utils configuration
    usage: /m4reload
    permission: m4utils.reload
  spawn:
    description: Teleporta você para o spawn do servidor
    usage: /spawn
    permission: m4utils.spawn
  modo:
    description: Abre um menu para selecionar o modo de jogo
    usage: /modo
    permission: m4utils.modo
  rtp:
    description: Teleporta aleatoriamente para algum lugar seguro
    usage: /rtp
    permission: m4utils.rtp
  home:
    description: Gerencia suas homes (criar, listar, teleportar)
    usage: /home [create|delete|tp|list|manage] [nome]
    permission: m4utils.home
    aliases: [homes, h]
  afk:
    description: Ativa/desativa o modo afk.
    usage: /afk
    permission: m4utils.afk
  warp:
    description: Permite teletransportar para locais comuns do servidor.
    usage: /warp
    permission: m4utils.warp
  scoreboard:
    description: Gerencia o sistema de scoreboard
    aliases: [sb]
    usage: /scoreboard <on|off|reload> [tipo]
  tablist:
    description: Gerencia o sistema de tablist
    aliases: [tl]
    usage: /tablist <reload|on|off>
    permission: m4utils.tablist

